[platformio]
default_envs = xiao_esp32c3
core_dir = .platformio-core

[env:xiao_esp32c3]
platform = espressif32@7.0.1
board = seeed_xiao_esp32c3
framework = arduino, espidf
board_build.partitions = partitions.csv
extra_scripts = pre:tools/platformio_release_metadata.py
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire@2.3.8
    milesburton/DallasTemperature@4.0.6
    https://github.com/joltwallet/esp_littlefs.git#v1.14.4
